[libraries.vunit_lib]
files = [
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/queue_pkg-body.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/dict_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/queue_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/integer_array_pkg-body.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/byte_vector_ptr_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/integer_array_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/types.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/string_ptr_pool_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/event_common_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/data_types_context.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/codec_builder.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/codec_builder-2008p.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/event_private_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/dict_pkg-2008p.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/data_types_private_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/codec-2008p.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/queue_pkg-2008p.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/integer_vector_ptr_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/integer_vector_ptr_pool_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/integer_vector_ptr_pkg-body-2002p.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/codec.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/dict_pkg-body.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/event_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/id_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/queue_pool_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/api/external_string_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/data_types/src/api/external_integer_vector_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/logging/src/location_pkg-body-2008m.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/logging/src/common_log_pkg-body.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/logging/src/ansi_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/logging/src/log_handler_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/logging/src/print_pkg-body.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/logging/src/print_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/logging/src/log_handler_pkg-body.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/logging/src/location_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/logging/src/logger_pkg-body.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/logging/src/common_log_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/logging/src/file_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/logging/src/log_levels_pkg-body.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/logging/src/log_levels_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/logging/src/logger_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/vunit_context.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/vunit_run_context.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/core/src/core_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/core/src/stop_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/core/src/stop_body_2008p.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/string_ops/src/string_ops.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/check/src/checker_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/check/src/checker_pkg-body.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/check/src/check.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/check/src/check_api.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/check/src/check_api-2008p.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/check/src/check-2008p.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/dictionary/src/dictionary.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/run/src/runner_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/run/src/run.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/run/src/run_types.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/run/src/run_api.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/path/src/path.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/com/src/com_api.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/com/src/com_context.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/com/src/com.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/com/src/com_deprecated.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/com/src/com_support.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/com/src/com_types.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/com/src/com_common.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/com/src/com_debug_codec_builder.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/com/src/com_string.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/com/src/com_messenger.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/vc_context.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/axi_stream_protocol_checker.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/stream_master_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/wishbone_slave.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/ram_master.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/memory_pkg-body.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/axi_read_slave.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/axi_lite_master_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/wishbone_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/axi_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/avalon_slave.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/stream_slave_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/avalon_stream_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/signal_checker_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/bus2memory.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/axi_stream_private_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/wishbone_master.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/uart_slave.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/memory_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/std_logic_checker.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/axi_stream_slave.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/vc_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/sync_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/avalon_sink.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/axi_stream_master.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/avalon_master.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/stream_master_pkg-body.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/uart_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/avalon_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/bus_master_pkg-body.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/axi_slave_private_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/memory_utils_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/stream_slave_pkg-body.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/avalon_source.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/bus_master_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/uart_master.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/sync_pkg-body.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/axi_stream_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/axi_write_slave.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/axi_slave_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/axi_stream_monitor.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/axi_statistics_pkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/verification_components/src/axi_lite_master.vhd"
]
[libraries.osvvm]
files = [
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/osvvm/MemorySupportPkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/osvvm/ScoreboardPkg_int.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/osvvm/RandomPkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/osvvm/NamePkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/osvvm/RandomBasePkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/osvvm/MessageListPkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/osvvm/OsvvmTypesPkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/osvvm/OsvvmScriptSettingsPkg_default.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/osvvm/MemoryPkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/osvvm/NameStorePkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/osvvm/RandomProcedurePkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/osvvm/OsvvmContext.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/osvvm/CoveragePkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/osvvm/ScoreboardPkg_slv.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/osvvm/MemoryGenericPkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/osvvm/ScoreboardGenericPkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/osvvm/OsvvmGlobalPkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/osvvm/TranscriptPkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/osvvm/ResolutionPkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/osvvm/AlertLogPkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/osvvm/OsvvmScriptSettingsPkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/osvvm/ReportPkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/osvvm/VendorCovApiPkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/osvvm/TextUtilPkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/osvvm/TbUtilPkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/osvvm/SortListPkg_int.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/osvvm/ResizePkg.vhd",
    "/home/marco/.local/lib/python3.13/site-packages/vunit/vhdl/osvvm/MessagePkg.vhd"
]
[libraries.neorv32]
files = [
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_package.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_sysinfo.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_fifo.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_twd.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_cpu_cp_bitmanip.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_gptmr.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_cpu_decompressor.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_onewire.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_cache.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_cpu_cp_cfu.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_trng.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_gpio.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_bus.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_debug_dm.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_bootloader_image.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_cpu.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_clint.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_cpu_cp_cond.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_cpu_cp_fpu.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_cpu_cp_crypto.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_debug_auth.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_wdt.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_neoled.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_cpu_cp_shifter.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_cpu_alu.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_cpu_frontend.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_sdi.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_cpu_cp_muldiv.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_uart.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_xbus.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_spi.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_boot_rom.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_pwm.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_imem.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_cpu_control.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_cfs.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_cpu_regfile.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_top.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_sys.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_cpu_pmp.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_slink.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_cpu_lsu.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_dma.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_cpu_counters.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_application_image.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_dmem.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_debug_dtm.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/core/neorv32_twi.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/test_setups/neorv32_test_setup_on_chip_debugger.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/test_setups/neorv32_test_setup_bootloader.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/test_setups/neorv32_test_setup_approm.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/processor_templates/neorv32_ProcessorTop_MinimalBoot.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/processor_templates/neorv32_ProcessorTop_Minimal.vhd",
    "/home/marco/development/fpga/neorv32-vogma/rtl/processor_templates/neorv32_ProcessorTop_UP5KDemo.vhd"
]
