[libraries]

lib.files = [
"sw/example/hello_cpp/neorv32_application_image.vhd",
"sw/example/hello_world/neorv32_application_image.vhd",
"sw/example/processor_check/neorv32_application_image.vhd",
"sw/example/game_of_life/neorv32_application_image.vhd",
"rtl/processor_templates/neorv32_ProcessorTop_MinimalBoot.vhd",
"rtl/processor_templates/neorv32_ProcessorTop_UP5KDemo.vhd",
"rtl/processor_templates/neorv32_ProcessorTop_Minimal.vhd",
"sim/sim_uart_rx.vhd",
"sim/neorv32_tb.vhd",
"rtl/test_setups/neorv32_test_setup_bootloader.vhd",
"rtl/test_setups/neorv32_test_setup_approm.vhd",
"rtl/test_setups/neorv32_test_setup_on_chip_debugger.vhd",
"sim/xbus_gateway.vhd",
"sim/xbus_memory.vhd",
"rtl/core/neorv32_package.vhd",
"rtl/core/neorv32_sysinfo.vhd",
"rtl/core/neorv32_twd.vhd",
"rtl/core/neorv32_cpu_cp_muldiv.vhd",
"rtl/core/neorv32_spi.vhd",
"rtl/system_integration/neorv32_vivado_ip.vhd",
"rtl/core/neorv32_xbus.vhd",
"rtl/core/neorv32_uart.vhd",
"rtl/core/neorv32_tracer.vhd",
"rtl/core/neorv32_boot_rom.vhd",
"rtl/system_integration/xbus2axi4_bridge.vhd",
"rtl/core/neorv32_sdi.vhd",
"rtl/core/neorv32_cpu_hwtrig.vhd",
"rtl/core/neorv32_cpu_frontend.vhd",
"rtl/core/neorv32_cpu_alu.vhd",
"rtl/core/neorv32_cpu_cp_shifter.vhd",
"rtl/system_integration/neorv32_litex_core_complex.vhd",
"rtl/core/neorv32_neoled.vhd",
"rtl/core/neorv32_prim.vhd",
"rtl/core/neorv32_cpu_counters.vhd",
"rtl/core/neorv32_application_image.vhd",
"rtl/core/neorv32_dma.vhd",
"rtl/core/neorv32_cpu_lsu.vhd",
"rtl/core/neorv32_slink.vhd",
"rtl/core/neorv32_cpu_pmp.vhd",
"rtl/core/neorv32_sys.vhd",
"rtl/system_integration/neorv32_libero_ip.vhd",
"rtl/core/neorv32_top.vhd",
"rtl/core/neorv32_cpu_regfile.vhd",
"rtl/core/neorv32_cfs.vhd",
"rtl/core/neorv32_cpu_control.vhd",
"rtl/core/neorv32_dmem.vhd",
"rtl/core/neorv32_imem.vhd",
"rtl/core/neorv32_pwm.vhd",
"rtl/core/neorv32_wdt.vhd",
"rtl/core/neorv32_debug_auth.vhd",
"rtl/core/neorv32_cpu_cp_crypto.vhd",
"rtl/core/neorv32_cpu_cp_fpu.vhd",
"rtl/core/neorv32_clint.vhd",
"rtl/core/neorv32_cpu_cp_cond.vhd",
"rtl/core/neorv32_cpu.vhd",
"rtl/core/neorv32_debug_dtm.vhd",
"rtl/core/neorv32_bootloader_image.vhd",
"rtl/core/neorv32_debug_dm.vhd",
"rtl/core/neorv32_bus.vhd",
"rtl/core/neorv32_gpio.vhd",
"rtl/core/neorv32_trng.vhd",
"rtl/core/neorv32_cpu_cp_cfu.vhd",
"rtl/core/neorv32_onewire.vhd",
"rtl/core/neorv32_cpu_decompressor.vhd",
"rtl/core/neorv32_gptmr.vhd",
"rtl/core/neorv32_cpu_cp_bitmanip.vhd",
"rtl/core/neorv32_twi.vhd",
"rtl/core/neorv32_cache.vhd",
]
